### ISSUE TITLE
Update to Node16

### ISSUE THREAD

**Issue by Sherlouk** [EmergeTools/emerge-upload-action#5]
> The node12 is not supported on macOS ARM64 platform. Use node16 instead.

Currently getting the above error on a macOS M1 runner, do we foresee any issues if we were to update this action to using node 16 instead? 👀

**Comment by ubiratansoares** [comment]
TIL : Github will [decommission node12 from Runners by mid August](https://github.blog/changelog/2023-07-17-github-actions-removal-of-node12-from-the-actions-runner/)

**Comment by NicoHinderling** [comment]
hey guys, apologies for the delay here. I've just bumped this action to run with node20. Let me know if you have any other issues!
